### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by macguy98** [boy0001/FastAsyncRedstone#1]
`[20:11:45 WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v16.11.11-8995ce2-368-9.11.0 generated an exception while executing task 31
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 16
        at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:233)
        at com.boydti.fawe.bukkit.v1_10.BukkitQueue_1_10.getCachedSection(BukkitQueue_1_10.java:65)
        at com.boydti.fawe.example.MappedFaweQueue.getOpacity(MappedFaweQueue.java:459)
        at com.boydti.far.QueueManager.computeSpreadBlockLight(QueueManager.java:185)
        at com.boydti.far.QueueManager.updateBlockLight(QueueManager.java:127)
        at com.boydti.far.QueueManager$1$1.run(QueueManager.java:42)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more`

Happens at random times and renders redstone useless.

**Comment by boy0001** [comment]
Redstone works regardless of whether the player can see it working.
