### ISSUE TITLE
It doesn't load on 1.8.x 

### ISSUE THREAD

**Issue by ChimpGamer** [boy0001/FastAsyncRedstone#18]
[21:53:10] [Server thread/INFO]: [FastAsyncRedstone] Injecting custom classes
[21:53:10] [Server thread/ERROR]: Could not load 'plugins/FastAsyncRedstone-16.12.03-e31de71-18-0.1.13.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: com.boydti.far.RedstoneSettings.load(Ljava/io/File;Ljava/lang/Class;)Z
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[custom.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[custom.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [custom.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [custom.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [custom.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [custom.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: com.boydti.far.RedstoneSettings.load(Ljava/io/File;Ljava/lang/Class;)Z
	at com.boydti.far.RedstoneSettings.load(RedstoneSettings.java:52) ~[?:?]
	at com.boydti.far.FarMain.setupConfig(FarMain.java:57) ~[?:?]
	at com.boydti.far.FarMain.<init>(FarMain.java:25) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[custom.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[custom.jar:git-Spigot-fdc1440-53fac9f]
	... 6 more

**Comment by Tosser42069** [comment]
The plugin is broken because the author hasn't updated it to work with the new FAWE.

**Comment by crazyhorse961** [comment]
So it would occur on every version?

**Comment by Tosser42069** [comment]
Yes, every version unless you used older FAWE versions. I am not sure how far back you'd have to go to correct this error.

**Comment by crazyhorse961** [comment]
Aw.. would be a pain trying with every version
