### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by L4BORG** [boy0001/FastAsyncRedstone#4]
```
[00:01:52] [Craft Scheduler Thread - 15/WARN]: java.util.ConcurrentModificationException
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:288)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at com.boydti.far.QueueManager$1$1.run(QueueManager.java:56)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:01:52] [Craft Scheduler Thread - 15/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: java.util.ConcurrentModificationException
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:288)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at com.boydti.far.QueueManager$1$1.run(QueueManager.java:56)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:02:08] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: java.util.ConcurrentModificationException
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:288)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at com.boydti.far.QueueManager$1$1.run(QueueManager.java:56)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:02:09] [Craft Scheduler Thread - 12/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: java.util.ConcurrentModificationException
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at com.boydti.fawe.bukkit.v1_8.BukkitQueue18R3.refreshChunk(BukkitQueue18R3.java:288)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at com.boydti.far.QueueManager$1$1.run(QueueManager.java:56)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[00:02:33] [Craft Scheduler Thread - 15/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

FastAsyncRedstone-16.11.13-f96cb79-9-0.1.4

```
[00:12:44 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[00:12:44 INFO]: Checking version, please wait...
[00:12:45 INFO]: You are running the latest version
```

**Comment by L4BORG** [comment]
Using FastAsyncWorldEdit-bukkit18-16.11.13-21de209-370-9.11.2 (and latest P2)

this would happen soon after copying active redstone clocks. After that redstone appeared bugged... until server restart.

**Comment by L4BORG** [comment]
Could be it redstone clock preventer causing this? (or maybe even just canceling redstone/piston events?)

**Comment by L4BORG** [comment]
Can not replicate with latest FAR and http://ci.athion.net/job/FastAsyncWorldEdit/376/ anymore...

**Comment by boy0001** [comment]
Yeah, I tried to fix it. Sorry for not responding.
