### ISSUE TITLE
Spigot 1.11 Support

### ISSUE THREAD

**Issue by mibby** [boy0001/FastAsyncRedstone#5]
FastAsyncRedstone dev 7
PaperSpigot (MC 1.11) dev 928

```
[22:03:06] [Server thread/INFO]: [FastAsyncRedstone] Enabling FastAsyncRedstone v1.0
[22:03:06] [Server thread/ERROR]: Error occurred while enabling FastAsyncRedstone v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/BlockPosition
	at com.boydti.far.FarMain.onEnable(FarMain.java:30) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.jar:git-Paper-928]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.jar:git-Paper-928]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.jar:git-Paper-928]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:377) [patched_1.11.jar:git-Paper-928]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:327) [patched_1.11.jar:git-Paper-928]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209) [patched_1.11.jar:git-Paper-928]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-928]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.BlockPosition
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.11.jar:git-Paper-928]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.jar:git-Paper-928]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_112]
	... 9 more
[22:03:06] [Server thread/INFO]: [FastAsyncRedstone] Disabling FastAsyncRedstone v1.0
```

**Comment by boy0001** [comment]
Updated.
