### ISSUE TITLE
could not load plugin

### ISSUE THREAD

**Issue by melinstagibson** [boy0001/FastAsyncRedstone#8]
`[06:48:05 INFO]: [FastAsyncRedstone] Injecting custom classes
[06:48:05 ERROR]: Could not load 'plugins/FastAsyncRedstone-16.11.28-a179350-15-0.1.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.11.jar:git-Paper-943]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [patched_1.11.jar:git-Paper-943]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:208) [patched_1.11.jar:git-Paper-943]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:599) [patched_1.11.jar:git-Paper-943]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:410) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:129) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:112) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:95) ~[patched_1.11.jar:git-Paper-943]
        at com.boydti.far.FarMain.<init>(FarMain.java:35) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.11.jar:git-Paper-943]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.11.jar:git-Paper-943]
        ... 6 more
`

paper 1.11 build #943, only with faredstone #11, #10 works

**Comment by L4BORG** [comment]
Same thing happens on 1.8.8

http://pastebin.com/73x0zKQS
